### ISSUE TITLE
lrbd missing RHEL 7

### ISSUE THREAD

**Issue by flowjo-mikej** [SUSE/lrbd#8]
The lrbd package doesn't seem to be available on the latest RHEL 7... Is there another repo I should be using?
# yum install lrbd

Loaded plugins: product-id, search-disabled-repos, subscription-manager
No package lrbd available.
Error: Nothing to do

**Comment by mikechristie** [comment]
ceph HA iSCSI support is planned in RHEL 7.3 and RHCS 2.1. There is no public code yet, because we are still working on it.

**Comment by flowjo-mikej** [comment]
Thank you for the clarification.

**Comment by cityvigil** [comment]
My OS is RHEL 7.3 ,how can I  install lrbd ?  Thanks 
-----------------

[root@node01 ~]# uname -a
Linux node01 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


[root@node01 ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@node01 ~]# LANG=C
[root@node01 ~]# yum install lrbd
Loaded plugins: fastestmirror, langpacks, priorities
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.tuna.tsinghua.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.cn99.com
8 packages excluded due to repository priority protections
No package lrbd available.
Error: Nothing to do


[root@node01 yum.repos.d]# ll
total 40
-rw-r--r--. 1 root root 1664 Nov 30  2016 CentOS-Base.repo
-rw-r--r--. 1 root root 1309 Nov 30  2016 CentOS-CR.repo
-rw-r--r--. 1 root root  649 Nov 30  2016 CentOS-Debuginfo.repo
-rw-r--r--. 1 root root  630 Nov 30  2016 CentOS-Media.repo
-rw-r--r--. 1 root root 1331 Nov 30  2016 CentOS-Sources.repo
-rw-r--r--. 1 root root 2893 Nov 30  2016 CentOS-Vault.repo
-rw-r--r--. 1 root root  314 Nov 30  2016 CentOS-fasttrack.repo
-rw-r--r--. 1 root root  573 Sep 14 11:13 ceph.repo
-rw-r--r--. 1 root root 1050 Jun 24 23:04 epel-testing.repo
-rw-r--r--. 1 root root  951 Jun 24 23:04 epel.repo
